name: SwiftRadioPlayer
options:
  bundleIdPrefix: com.flyingpingu
  deploymentTarget:
    iOS: 15.0
    macOS: 11.0
    tvOS: 15.0
targets:
  SwiftRadioPlayer:
    type: framework
    platform: [iOS]
    sources: Sources/SwiftRadioPlayer
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
  SwiftRadioPlayer_mac:
    type: framework
    platform: [macOS]
    sources: Sources/SwiftRadioPlayer
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
  SwiftRadioPlayer_tvOS:
    type: framework
    platform: [tvOS]
    sources: Sources/SwiftRadioPlayer
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
