name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-15-arm64

    strategy:
      matrix:
        build: [
          { destination: "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.4", scheme: "SwiftRadioPlayer-Example", sdk: "iphonesimulator18.4" },
        ]

    steps:
    - uses: actions/checkout@v2

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod install --project-directory=Example

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild \
          -workspace Example/SwiftRadioPlayer.xcworkspace \
          -scheme ${{ matrix.build.scheme }} \
          -sdk ${{ matrix.build.sdk }} \
          -destination "${{ matrix.build.destination }}" \
          -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c

    - name: Validate Podspec
      run: pod lib lint --quick
